### ISSUE TITLE
使用css定制滚动条样式之后表格滚动条被遮挡

### ISSUE THREAD

**Issue by elewen** [x-extends/vxe-table#1105]
给项目添加如下样式定制滚动条：

```css
// 滚动条
::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}

// 滚动条背景
::-webkit-scrollbar-track-piece {
  background-color: #d4e9e2;
  -webkit-border-radius: 4px;
}

// 滚动条滑块
::-webkit-scrollbar-thumb {
  background-color: #00754a;
  -webkit-border-radius: 4px;
}
```

这时候观察有滚动条的表格，发现滚动条显示不完整。
通过修改如下 div 的 css 可以让滚动条显示完整，然而会导致其他新的显示问题。

改动前：

```html
<div class="vxe-table--border-line"></div>
```

第一种改法：

```html
<div class="vxe-table--border-line" style="box-sizing: content-box;"></div>
```

第二种改法：

```html
<div class="vxe-table--border-line" style="display: none;"></div>
```

-------

官方给出的 [滚动条样式](https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/scrollStyle) 的示例看起来滚动条显示是完整的，但这只是假象。实际上是通过给滑块添加 border 弱化了这个问题。
如果把该示例的样式中 border 注释掉马上原形必露。

```css
.mytable-scrollbar div::-webkit-scrollbar-thumb {
  background-color: #bfbfbf;
  border-radius: 5px;
  /* border: 1px solid #F1F1F1; */
  box-shadow: inset 0 0 6px rgba(0,0,0,.3);
}
```

这实际上是拆东墙补西墙的做法，希望官方能够给出靠谱的解决方案，谢谢。
