### ISSUE TITLE
使用css定制滚动条样式之后表格滚动条被遮挡

### ISSUE THREAD

**Issue by elewen** [x-extends/vxe-table#1106]

**Comment by elewen** [comment]
已通过添加如下样式解决了问题，但是滚动表格内容到最上面或最右面时会出现双边框，此外还会不会导致其他 bug 不得而知：
```css
.vxe-table .vxe-table--border-line {
  box-sizing: content-box;
  top: -1px;
  left: -1px;
}
```
