### ISSUE TITLE
当同时使用expand展开行，fixed固定列和show-overflow，会出现展开行的内容出现在固定列 

### ISSUE THREAD

**Issue by HeYinJie** [x-extends/vxe-table#1564]
**（必填）请填写问题描述或截图：**
![image](https://user-images.githubusercontent.com/41420737/140868889-43f91050-9e5f-4fdb-a9e7-29de355d9519.png)
![image](https://user-images.githubusercontent.com/41420737/140868905-7d8ad6db-60b1-4324-8515-fa2ddf4e1ef4.png)

**（必填）请填在线链接：**
https://jsrun.net/ItWKp/edit

**（必填）请填写期望的结果：**
固定列上不要展示展开行里面的内容

**（必填）请填写以下信息：**

- OS: windows
- Browser: 谷歌
- vue: 2.6
- vxe-table: 3.4.4

**Comment by czkm** [comment]
现在有解决方案吗 ，是不是只能自己取用css样式控制/？

**Comment by kimihiro233** [comment]
@xe-bot

**Comment by VincentDream** [comment]
@czkm css如何解决呢？有没有其他解决方案？

**Comment by guahunyo** [comment]
我是想解决expand显示在fixed上面了改z-index不管用

**Comment by zqy233** [comment]
我是这样写的
```css
.vxe-table--fixed-wrapper {
  .vxe-body--expanded-cell {
    .vxe-table--header-wrapper {
      visibility: hidden;
    }
    .fixed-left--wrapper {
      visibility: hidden;
    }
  }
}
```
