### ISSUE TITLE
vxe-grid虚拟滚动左固定右固定表头每一项宽度分配异常

### ISSUE THREAD

**Issue by aslrz-club** [x-extends/vxe-table#1619]
### 可复现的链接：

https://codesandbox.io/s/clever-morning-i7bsi?file=/src/App.vue

### 问题描述与截图：

vxe-grid超过100条启动虚拟滚动 复制的左固定 右固定的表头似乎平分的整个表格宽度，导致宽度显示异常

### 期望的结果：

希望和没启动虚拟滚动和设置width保持一致

### 操作系统：

win11

### 浏览器版本：

Chrome 96.0.4664.110（正式版本） （64 位）

### vue 版本：

3.2.6

### vxe-table 版本：

4.1.18

**Comment by transtone** [comment]
不止宽度，自定义表头的高度也有问题。
目前是这样临时解决的：
```css
.is--virtual-y.vxe-table--render-default.size--mini.cust-header {
  .vxe-header--column.col--ellipsis {
    height: 60px;
  }

  .vxe-header--column.col--ellipsis > .vxe-cell {
    max-height: 60px;
  }

  .vxe-table--fixed-left-wrapper,
  .vxe-table--fixed-right-wrapper {
    .vxe-table--header-wrapper.fixed-right--wrapper,
    .vxe-table--header-wrapper.fixed-left--wrapper {
      width: 100%;

      table.vxe-table--header {
        width: calc(100% + 1Px) !important;
      }
    }
  }
}

```
