### ISSUE TITLE
proxyConfig 增加不显示loading

### ISSUE THREAD

**Issue by sukney** [x-extends/vxe-table#1652]
### 这个需求解决了什么问题：

在vue框架 中 一般有自己的loading，需要增加取消该loading，用框架的loading

### 建议的 API 是什么样的：

proxyConfig: {
    loading:false,
    autoLoad: true,
    enabled: false,

loading:false  就不显示loading

**Comment by xlz26296** [comment]
添加样式就可以去掉表格默认的loading了
```css
.vxe-table .vxe-loading {
  display: none;
}
```
