### ISSUE TITLE
windows下 pulldown组件 下拉table 无法使用滚动条

### ISSUE THREAD

**Issue by GGBeng1** [x-extends/vxe-table#1940]
### 可复现的链接：

https://vxetable.cn/v3/#/table/module/pulldown

### 问题描述与截图：

点击下拉分页表格
<img width="961" alt="image" src="https://user-images.githubusercontent.com/40552498/210040695-aec2075d-6ec9-4ac1-92b8-9dc101abe22e.png">

### 期望的结果：

可以正常使用滚动条

### 操作系统：

windows11

### 浏览器版本：

chrome 108

### vue 版本：

2.7.14

### vxe-table 版本：

3.6.9

**Comment by jincy1** [comment]
我也碰到这个问题，增加全局样式
```scss
.vxe-pulldown--panel.animat--leave {
  transform-style: flat !important;
}
```
暂时解决问题
