### ISSUE TITLE
自适应行高后 fixed的列无法自适应高度

### ISSUE THREAD

**Issue by wukongyang** [x-extends/vxe-table#2637]
### 可复现的链接（包含复现链接与示例代码）：

无

### 问题描述与截图：

![image](https://github.com/user-attachments/assets/e2c06db4-4bb5-44da-a34e-37ab5ac0f962)

### 操作系统：

mac

### 浏览器版本：

版本 130.0.6723.117（正式版本） (arm64)

### vue 版本：

3.5.11

### vxe-pc-ui 版本：

4.2.51

### vxe-table 版本：

4.8.13

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by xkxk1995** [comment]
我也出现了这种问题 不知道有没有解决方案

**Comment by qq1031824970** [comment]
我是列数比较多自定义单元格比较多滚动时下边几行固定列经常没展开高度，容易错位。暂时用样式去设置固定列了

**Comment by xkxk1995** [comment]
```css
//左fixed滚动条 如vxetable修复了fixed滚动条问题需要删除
.vxe-table--fixed-left-wrapper {
  fixed-left--wrapper::-webkit-scnollbar {
    display: none.
  }
}

//滚动条消失后问题
vxe-table--body-wrapper.fixed-left--wrapper:has(+.vxe-table--footer-wrapper){
//!这里设置的是常规有footer的 如果vxetable修复了fixed错位问题需要删除
  height:calc(100%-81px)!important;
}
```
这里设置了左侧滚动条消失，然后设置了行高后 会存在滚动条拉到最底部错位问题
设置了这个style作为临时解决方案
