### ISSUE TITLE
希望改进筛选器中checkbox实现方式

### ISSUE THREAD

**Issue by natee** [x-extends/vxe-table#655]
### 请填写问题描述 Describe

当前筛选器中checkbox是两个伪元素 + 绝对定位实现，这样会使得自定义筛选器样式变得很困难：

- 当修改了外层`li`元素的`line-height`或`padding`，会导致复选框的定位难以维护

![1](https://user-images.githubusercontent.com/4928035/72511202-b6637a80-3885-11ea-93c0-532febe37a15.png)

必须同时正确计算三个属性然后覆盖：
```scss
     &:before {
        top: 9px; // 强依赖li的line-height或padding
      }
      &.is--checked {
        &:after {
          top: 11px;
        }
      }
      &.is--indeterminate {
        &:after {
          top: 15px;
        }
      }
```

 **建议增加一个标签，这样只需要考虑这个标签的位置属性即可。**

### 请填写版本号 Version

- vxe-table: 2.8.0-beta.1
