### ISSUE TITLE
表格数据显示问题

### ISSUE THREAD

**Issue by uchiyo** [x-extends/vxe-table#925]
**（必填）请填写问题描述或截图**
如果名称包含有多个空格，表格自己会过滤掉只显示一个空格，导致用户无法知道具体空格数而无法正确搜索名称，
但是点编辑的时候又能具体显示所有空格数（语言表达不清晰，具体请看示例）

比如输入：115   111   222（中间隔三个空格）
vxe-table表格却显示：115 11 222（表格只显示一个空格数），而非显示用户具体输入的空格数

**（必填）请填在线链接**
http://jsrun.net/vcWKp/edit

**（必填）请填写期望的结果**
希望能显示用户原原本本的数据

**（必填）请填写以下信息：**

- OS: win10
- Browser: chrome
- vue: 2.6.11
- vxe-table: 2.9.11

**Comment by xlz26296** [comment]
html会自动忽略连续的空格只显示一个，你可以转成 \&nbsp; 或者通过修改cell样式（兼容性自己去测试哈）
```css
.my-table .vxe-cell {
  white-space: pre !important;
}
```
